galaxy_info:
  author: Skupper team
  company: Red Hat
  description: Creates a token to a given host and save it as a host variable
  issue_tracker_url: https://github.com/skupper/skupper-ansible/issues
  license: Apache-2.0
  min_ansible_version: "2.1"
  platforms:
    - name: EL
    - name: Fedora
    - name: GenericLinux

  galaxy_tags:
    - skupper
    - token

dependencies:
  - role: skupper_option
