- name: Validate kubernetes flags
  ansible.builtin.include_tasks: kube-validate.yml

- name: Prepare init command
  ansible.builtin.include_tasks: kube-command.yml

- name: Ensure provided namespace exist
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  when: namespace is defined and namespace | length() > 0
