galaxy_info:
  author: Skupper team
  company: Red Hat
  description: Creates links to other Skupper sites
  issue_tracker_url: https://github.com/skupper/skupper-ansible/issues
  license: Apache-2.0
  min_ansible_version: "2.1"
  platforms:
    - name: EL
    - name: Fedora
    - name: GenericLinux

  galaxy_tags:
    - skupper
    - link

dependencies:
  - role: skupper_option
