- name: Preparing init command
  set_fact:
    skupper_init_command:
      - skupper
      - init
      - --platform
      - "{{ platform }}"

- name: Adding --kubeconfig
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--kubeconfig', kubeconfig] }}"
  when: kubeconfig is defined and kubeconfig | length() > 0

- name: Adding --context
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--context', context] }}"
  when: context is defined and context | length() > 0

- name: Adding --namespace
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--namespace', namespace] }}"
  when: namespace is defined and namespace | length() > 0

- name: Adding --site-name
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--site-name', init.siteName] }}"
  when: init['siteName'] is defined

- name: Adding --ingress
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--ingress', init.ingress] }}"
  when: init['ingress'] is defined

- name: Adding --router-mode
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-mode', init.routerMode] }}"
  when: init['routerMode'] is defined

- name: Adding --labels
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--labels', item] }}"
  with_items: "{{ init['labels'] }}"
  when: init['labels'] is defined and init['labels'] | length() > 0

- name: Adding --router-logging
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-logging', init.routerLogging] }}"
  when: init['routerLogging'] is defined

- name: Adding --router-debug-mode
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-debug-mode', init.routerDebugMode] }}"
  when: init['routerDebugMode'] is defined

- name: Adding --timeout
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--timeout', init.timeout] }}"
  when: init['timeout'] is defined

- name: Adding --ingress-host
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--ingress-host', init.ingressHost] }}"
  when: init['ingressHost'] is defined

- name: Adding --create-network-policy
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--create-network-policy', init.createNetworkPolicy] }}"
  when: init['createNetworkPolicy'] is defined

- name: Adding --enable-service-sync
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--enable-service-sync=' + init.enableServiceSync] }}"
  when: init['enableServiceSync'] is defined

- name: Adding --enable-console
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--enable-console', init.enableConsole] }}"
  when: init['enableConsole'] is defined

- name: Adding --console-auth
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--console-auth', init.consoleAuth] }}"
  when: init['consoleAuth'] is defined

- name: Adding --console-user
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--console-user', init.consoleUser] }}"
  when: init['consoleUser'] is defined

- name: Adding --console-password
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--console-password', init.consolePassword] }}"
  when: init['consolePassword'] is defined

- name: Adding --console-ingress
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--console-ingress', init.consoleIngress] }}"
  when: init['consoleIngress'] is defined

- name: Adding --annotations
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--annotations', item] }}"
  with_items: "{{ init['annotations'] }}"
  when: init['annotations'] is defined and init['annotations'] | length() > 0

- name: Adding --ingress-annotations
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--ingress-annotations', item] }}"
  with_items: "{{ init['ingressAnnotations'] }}"
  when: init['ingressAnnotations'] is defined and init['ingressAnnotations'] | length() > 0

- name: Adding --router-service-annotations
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-service-annotations', item] }}"
  with_items: "{{ init['routerServiceAnnotations'] }}"
  when: init['routerServiceAnnotations'] is defined and init['routerServiceAnnotations'] | length() > 0

- name: Adding --controller-service-annotations
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-service-annotations', item] }}"
  with_items: "{{ init['controllerServiceAnnotations'] }}"
  when: init['controllerServiceAnnotations'] is defined and init['controllerServiceAnnotations'] | length() > 0

- name: Adding --routers
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--routers', init.routers] }}"
  when: init['routers'] is defined

- name: Adding --router-cpu
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-cpu', init.routerCpu] }}"
  when: init['routerCpu'] is defined

- name: Adding --router-memory
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-memory', init.routerMemory] }}"
  when: init['routerMemory'] is defined

- name: Adding --router-cpu-limit
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-cpu-limit', init.routerCpuLimit] }}"
  when: init['routerCpuLimit'] is defined

- name: Adding --router-memory-limit
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-memory-limit', init.routerMemoryLimit] }}"
  when: init['routerMemoryLimit'] is defined

- name: Adding --router-node-selector
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-node-selector', init.routerNodeSelector] }}"
  when: init['routerNodeSelector'] is defined

- name: Adding --router-pod-affinity
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-pod-affinity', init.routerPodAffinity] }}"
  when: init['routerPodAffinity'] is defined

- name: Adding --router-pod-antiaffinity
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-pod-antiaffinity', init.routerPodAntiaffinity] }}"
  when: init['routerPodAntiaffinity'] is defined

- name: Adding --router-ingress-host
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-ingress-host', init.routerIngressHost] }}"
  when: init['routerIngressHost'] is defined

- name: Adding --router-load-balancer-ip
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-load-balancer-ip', init.routerLoadBalancerIp] }}"
  when: init['routerLoadBalancerIp'] is defined

- name: Adding --controller-cpu
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-cpu', init.controllerCpu] }}"
  when: init['controllerCpu'] is defined

- name: Adding --controller-memory
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-memory', init.controllerMemory] }}"
  when: init['controllerMemory'] is defined

- name: Adding --controller-cpu-limit
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-cpu-limit', init.controllerCpuLimit] }}"
  when: init['controllerCpuLimit'] is defined

- name: Adding --controller-memory-limit
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-memory-limit', init.controllerMemoryLimit] }}"
  when: init['controllerMemoryLimit'] is defined

- name: Adding --controller-node-selector
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-node-selector', init.controllerNodeSelector] }}"
  when: init['controllerNodeSelector'] is defined

- name: Adding --controller-pod-affinity
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-pod-affinity', init.controllerPodAffinity] }}"
  when: init['controllerPodAffinity'] is defined

- name: Adding --controller-pod-antiaffinity
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-pod-antiaffinity', init.controllerPodAntiaffinity] }}"
  when: init['controllerPodAntiaffinity'] is defined

- name: Adding --controller-ingress-host
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-ingress-host', init.controllerIngressHost] }}"
  when: init['controllerIngressHost'] is defined

- name: Adding --controller-load-balancer-ip
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-load-balancer-ip', init.controllerLoadBalancerIp] }}"
  when: init['controllerLoadBalancerIp'] is defined

- name: Adding --config-sync-cpu
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--config-sync-cpu', init.configSyncCpu] }}"
  when: init['configSyncCpu'] is defined

- name: Adding --config-sync-memory
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--config-sync-memory', init.configSyncMemory] }}"
  when: init['configSyncMemory'] is defined

- name: Adding --config-sync-cpu-limit
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--config-sync-cpu-limit', init.configSyncCpuLimit] }}"
  when: init['configSyncCpuLimit'] is defined

- name: Adding --config-sync-memory-limit
  set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--config-sync-memory-limit', init.configSyncMemoryLimit] }}"
  when: init['configSyncMemoryLimit'] is defined
