---
# Create a temporary file to store the token
- name: Create temporary file for token
  ansible.builtin.tempfile:
    state: file
    suffix: tokentemp
  register: tokentemp

# Add the temp file name to the token create command
- name: Adding temporary file name to token create command
  ansible.builtin.set_fact:
    skupper_token_command: "{{ skupper_token_command + [tokentemp.path] }}"

# executing and validating result
- name: Executing skupper token create
  ansible.builtin.command:
    argv: "{{ skupper_token_command }}"
  register: tokenStatus
  changed_when: not tokenStatus.failed

# reading generated token
- name: Reading token
  ansible.builtin.command: "cat {{ tokentemp.path }}"
  register: tokenContent
  changed_when: not tokenContent.failed

# saving generated token into tokens dictionary
- name: Saving token into tokens dictionary
  ansible.builtin.set_fact:
    generatedToken: "{{ tokenContent.stdout }}"

# remove the generated token file
- name: Remove generated token file
  ansible.builtin.file:
    path: "{{ tokentemp.path }}"
    state: absent
