galaxy_info:
  author: Skupper team
  company: Red Hat
  description: Deploys your whole Skupper network
  issue_tracker_url: https://github.com/skupper/skupper-ansible/issues
  license: Apache-2.0
  min_ansible_version: "2.1"
  platforms:
    - name: EL
    - name: Fedora
    - name: GenericLinux

  galaxy_tags:
    - skupper
    - init
    - token
    - link
    - service
    - bind
    - expose

dependencies:
  - role: skupper_common
  - role: skupper_init
  - role: skupper_token
  - role: skupper_link
  - role: skupper_service
